### ISSUE TITLE
LSTM and heading networks building fail

### ISSUE THREAD

**Issue by anisghaoui** [Sachini/ronin#14]
Hi,
First thanks a lot for providing this repo and excellent work.

I was able to easily run Resnet and TCN but there is a struggle with LSTM and thus the heading network.
Considering the follow shell command :
```
python3 source/ronin_lstm_tcn.py \
test \
--type lstm \
--test_list lists/list_test_unseen.txt \
--root_dir datasets/RoNIN_dataset/unseen_subjects_test_set \
--data_dir datasets/RoNIN_dataset/unseen_subjects_test_set \
--out_dir output \
--model_path pretrained_models/ronin_lstm/checkpoints/ronin_lstm_checkpoint.pt \
--fast_test
```
I get : 

```
a006_2: device: samsung1, ori_error (game_rv): 3.978
Simple LSTM Network
Network constructed. trainable parameters: 205832
Traceback (most recent call last):
  File "source/ronin_lstm_tcn.py", line 543, in <module>
    test(args, **kwargs)
  File "source/ronin_lstm_tcn.py", line 366, in test
    network.load_state_dict(checkpoint.get('model_state_dict'))
  File "/home/anis/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LSTMSeqNetwork:
        Unexpected key(s) in state_dict: "bilinear.weight", "bilinear.bias". 
        size mismatch for lstm.weight_ih_l0: copying a param with shape torch.Size([400, 30]) from checkpoint, the shape in current model is torch.Size([400, 6]).
        size mismatch for linear1.weight: copying a param with shape torch.Size([10, 130]) from checkpoint, the shape in current model is torch.Size([10, 100]).
```

I might be missing something rather simple, but I believe that pyTorch isn't loading correctly the model.
I get the same problem when trying to load the heading network since it is LSTM based.
is it possible that this is Pytorch version related?

Thank you for your time.

**Comment by Sachini** [comment]
You have missed the config path argument I believe.
`--config pretrained_models/ronin_lstm/config.json`

**Comment by Sachini** [comment]
As mentioned in the paper, we use lstm with bilinear layer, which is `--type lstm_bi`. Alternatively you can use the config file that comes with the checkpoint
