### ISSUE TITLE
How to solve the UnicodeDecodeError?

### ISSUE THREAD

**Issue by pklim101** [Sachini/ronin#50]
When I run the cmd : python source/ronin_resnet.py --mode train --train_list "mydataset/a027_1/data.hdf5" --root_dir "mydataset" --out_dir "my_out",
then, it has the follow error：

Traceback (most recent call last):
  File "/ronin/source/ronin_resnet.py", line 423, in <module>
    train(args)
  File "/ronin/source/ronin_resnet.py", line 103, in train
    train_dataset = get_dataset_from_list(args.root_dir, args.train_list, args, mode='train')
  File "/ronin/source/ronin_resnet.py", line 96, in get_dataset_from_list
    data_list = [s.strip().split(',' or ' ')[0] for s in f.readlines() if len(s) > 0 and s[0] != '#']
  File "/opt/anaconda3/envs/py397/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by pklim101** [comment]
I know the reason which is --train_list "lists/list_train.txt"
