### ISSUE TITLE
How to solve it which the Error is checkpoint_0.pt cannot be opened when I run the train task?

### ISSUE THREAD

**Issue by pklim101** [Sachini/ronin#51]
Training set loaded. Feature size: 6, target size: 2. Time usage: 5.519s
Number of train samples: 761740
Total number of parameters:  4634882
Start from epoch 0
[W NNPACK.cpp:53] Could not initialize NNPACK! Reason: Unsupported hardware.
-------------------------
Init: average loss: [0.347481 0.348557]/0.348019
-------------------------
Epoch 0, time usage: 10319.676s, average loss: [0.050121 0.051044]/0.050582
Traceback (most recent call last):
  File /ronin/source/ronin_resnet.py", line 423, in <module>
    train(args)
  File "/ronin/source/ronin_resnet.py", line 227, in train
    torch.save({'model_state_dict': network.state_dict(),
  File "/opt/anaconda3/envs/py397/lib/python3.9/site-packages/torch/serialization.py", line 422, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/opt/anaconda3/envs/py397/lib/python3.9/site-packages/torch/serialization.py", line 309, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/opt/anaconda3/envs/py397/lib/python3.9/site-packages/torch/serialization.py", line 287, in __init__
    super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: File my_out/checkpoints/checkpoint_0.pt cannot be opened.

**Comment by pklim101** [comment]
The reason is that the disk have no more space.
